FROM node:8.1.2-wheezy
WORKDIR /root
RUN apt-get update; apt-get install rsync -y
RUN git clone https://github.com/toolkit-for-ynab/toolkit-for-ynab
WORKDIR /root/toolkit-for-ynab
RUN git checkout 9ca8ac1
RUN npm install
RUN ./build
CMD [ "/bin/bash" ]
